parameters:
    tn_sculpin.path_navigation.generator.class: Tn\Bundle\PathNavigationBundle\PathNavigationGenerator
    tn_sculpin.path_navigation.data_provider.class: Tn\Bundle\PathNavigationBundle\PathNavigationProvider
    tn_sculpin.tag_navigation.twig_function.class: Tn\Bundle\PathNavigationBundle\Twig\PathNavigationExtension
    tn_sculpin.path_navigation.permalink_factory.class: Tn\Bundle\PathNavigationBundle\Permalink\PermalinkFactory

services:
    tn_sculpin.path_navigation.generator:
        class: %tn_sculpin.path_navigation.generator.class%
        arguments:
            - @sculpin_content_types.types.videos.data_provider
            - @sculpin_content_types.types.articles.data_provider
            - @tn_sculpin.path_navigation.data_provider
            - @tn_sculpin.path_navigation.permalink_factory
        tags:
            - { name: sculpin.generator, alias: tn_path_navigation }

    tn_sculpin.path_navigation.data_provider:
        class: %tn_sculpin.path_navigation.data_provider.class%
        arguments:
            - @sculpin_content_types.types.videos.data_provider
            - @sculpin_content_types.types.articles.data_provider
        tags:
            - { name: sculpin.data_provider, alias: tn_posts_dates }

    tn_sculpin.tag_navigation.twig_function:
        class: %tn_sculpin.tag_navigation.twig_function.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    tn_sculpin.path_navigation.permalink_factory:
        class: %tn_sculpin.path_navigation.permalink_factory.class%
        arguments:
            - %tn_sculpin.path_navigation.permalink.mask_year%
            - %tn_sculpin.path_navigation.permalink.mask_month%